################################################################################
# Automatically-generated file. Do not edit!
# Toolchain: GNU Tools for STM32 (9-2020-q2-update)
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
C:/Users/alejo/Documents/containers-project/D-Box/FreeRTOS/Demo/FreeRTOS-BOX-MODBUS_PID/ST_Code/Drivers/STM32L1xx_HAL_Driver/Src/stm32l1xx_hal.c \
C:/Users/alejo/Documents/containers-project/D-Box/FreeRTOS/Demo/FreeRTOS-BOX-MODBUS_PID/ST_Code/Drivers/STM32L1xx_HAL_Driver/Src/stm32l1xx_hal_cortex.c \
C:/Users/alejo/Documents/containers-project/D-Box/FreeRTOS/Demo/FreeRTOS-BOX-MODBUS_PID/ST_Code/Drivers/STM32L1xx_HAL_Driver/Src/stm32l1xx_hal_dma.c \
C:/Users/alejo/Documents/containers-project/D-Box/FreeRTOS/Demo/FreeRTOS-BOX-MODBUS_PID/ST_Code/Drivers/STM32L1xx_HAL_Driver/Src/stm32l1xx_hal_flash.c \
C:/Users/alejo/Documents/containers-project/D-Box/FreeRTOS/Demo/FreeRTOS-BOX-MODBUS_PID/ST_Code/Drivers/STM32L1xx_HAL_Driver/Src/stm32l1xx_hal_flash_ex.c \
C:/Users/alejo/Documents/containers-project/D-Box/FreeRTOS/Demo/FreeRTOS-BOX-MODBUS_PID/ST_Code/Drivers/STM32L1xx_HAL_Driver/Src/stm32l1xx_hal_flash_ramfunc.c \
C:/Users/alejo/Documents/containers-project/D-Box/FreeRTOS/Demo/FreeRTOS-BOX-MODBUS_PID/ST_Code/Drivers/STM32L1xx_HAL_Driver/Src/stm32l1xx_hal_gpio.c \
C:/Users/alejo/Documents/containers-project/D-Box/FreeRTOS/Demo/FreeRTOS-BOX-MODBUS_PID/ST_Code/Drivers/STM32L1xx_HAL_Driver/Src/stm32l1xx_hal_pwr.c \
C:/Users/alejo/Documents/containers-project/D-Box/FreeRTOS/Demo/FreeRTOS-BOX-MODBUS_PID/ST_Code/Drivers/STM32L1xx_HAL_Driver/Src/stm32l1xx_hal_pwr_ex.c \
C:/Users/alejo/Documents/containers-project/D-Box/FreeRTOS/Demo/FreeRTOS-BOX-MODBUS_PID/ST_Code/Drivers/STM32L1xx_HAL_Driver/Src/stm32l1xx_hal_rcc.c \
C:/Users/alejo/Documents/containers-project/D-Box/FreeRTOS/Demo/FreeRTOS-BOX-MODBUS_PID/ST_Code/Drivers/STM32L1xx_HAL_Driver/Src/stm32l1xx_hal_rcc_ex.c \
C:/Users/alejo/Documents/containers-project/D-Box/FreeRTOS/Demo/FreeRTOS-BOX-MODBUS_PID/ST_Code/Drivers/STM32L1xx_HAL_Driver/Src/stm32l1xx_hal_tim.c \
C:/Users/alejo/Documents/containers-project/D-Box/FreeRTOS/Demo/FreeRTOS-BOX-MODBUS_PID/ST_Code/Drivers/STM32L1xx_HAL_Driver/Src/stm32l1xx_hal_tim_ex.c \
C:/Users/alejo/Documents/containers-project/D-Box/FreeRTOS/Demo/FreeRTOS-BOX-MODBUS_PID/ST_Code/Drivers/STM32L1xx_HAL_Driver/Src/stm32l1xx_hal_uart.c \
C:/Users/alejo/Documents/containers-project/D-Box/FreeRTOS/Demo/FreeRTOS-BOX-MODBUS_PID/ST_Code/Drivers/STM32L1xx_HAL_Driver/Src/stm32l1xx_ll_dma.c \
C:/Users/alejo/Documents/containers-project/D-Box/FreeRTOS/Demo/FreeRTOS-BOX-MODBUS_PID/ST_Code/Drivers/STM32L1xx_HAL_Driver/Src/stm32l1xx_ll_exti.c \
C:/Users/alejo/Documents/containers-project/D-Box/FreeRTOS/Demo/FreeRTOS-BOX-MODBUS_PID/ST_Code/Drivers/STM32L1xx_HAL_Driver/Src/stm32l1xx_ll_gpio.c \
C:/Users/alejo/Documents/containers-project/D-Box/FreeRTOS/Demo/FreeRTOS-BOX-MODBUS_PID/ST_Code/Drivers/STM32L1xx_HAL_Driver/Src/stm32l1xx_ll_pwr.c \
C:/Users/alejo/Documents/containers-project/D-Box/FreeRTOS/Demo/FreeRTOS-BOX-MODBUS_PID/ST_Code/Drivers/STM32L1xx_HAL_Driver/Src/stm32l1xx_ll_rcc.c \
C:/Users/alejo/Documents/containers-project/D-Box/FreeRTOS/Demo/FreeRTOS-BOX-MODBUS_PID/ST_Code/Drivers/STM32L1xx_HAL_Driver/Src/stm32l1xx_ll_usart.c \
C:/Users/alejo/Documents/containers-project/D-Box/FreeRTOS/Demo/FreeRTOS-BOX-MODBUS_PID/ST_Code/Drivers/STM32L1xx_HAL_Driver/Src/stm32l1xx_ll_utils.c 

OBJS += \
./ST_Code/Drivers/STM32L1xx_HAL_Driver/Src/stm32l1xx_hal.o \
./ST_Code/Drivers/STM32L1xx_HAL_Driver/Src/stm32l1xx_hal_cortex.o \
./ST_Code/Drivers/STM32L1xx_HAL_Driver/Src/stm32l1xx_hal_dma.o \
./ST_Code/Drivers/STM32L1xx_HAL_Driver/Src/stm32l1xx_hal_flash.o \
./ST_Code/Drivers/STM32L1xx_HAL_Driver/Src/stm32l1xx_hal_flash_ex.o \
./ST_Code/Drivers/STM32L1xx_HAL_Driver/Src/stm32l1xx_hal_flash_ramfunc.o \
./ST_Code/Drivers/STM32L1xx_HAL_Driver/Src/stm32l1xx_hal_gpio.o \
./ST_Code/Drivers/STM32L1xx_HAL_Driver/Src/stm32l1xx_hal_pwr.o \
./ST_Code/Drivers/STM32L1xx_HAL_Driver/Src/stm32l1xx_hal_pwr_ex.o \
./ST_Code/Drivers/STM32L1xx_HAL_Driver/Src/stm32l1xx_hal_rcc.o \
./ST_Code/Drivers/STM32L1xx_HAL_Driver/Src/stm32l1xx_hal_rcc_ex.o \
./ST_Code/Drivers/STM32L1xx_HAL_Driver/Src/stm32l1xx_hal_tim.o \
./ST_Code/Drivers/STM32L1xx_HAL_Driver/Src/stm32l1xx_hal_tim_ex.o \
./ST_Code/Drivers/STM32L1xx_HAL_Driver/Src/stm32l1xx_hal_uart.o \
./ST_Code/Drivers/STM32L1xx_HAL_Driver/Src/stm32l1xx_ll_dma.o \
./ST_Code/Drivers/STM32L1xx_HAL_Driver/Src/stm32l1xx_ll_exti.o \
./ST_Code/Drivers/STM32L1xx_HAL_Driver/Src/stm32l1xx_ll_gpio.o \
./ST_Code/Drivers/STM32L1xx_HAL_Driver/Src/stm32l1xx_ll_pwr.o \
./ST_Code/Drivers/STM32L1xx_HAL_Driver/Src/stm32l1xx_ll_rcc.o \
./ST_Code/Drivers/STM32L1xx_HAL_Driver/Src/stm32l1xx_ll_usart.o \
./ST_Code/Drivers/STM32L1xx_HAL_Driver/Src/stm32l1xx_ll_utils.o 

C_DEPS += \
./ST_Code/Drivers/STM32L1xx_HAL_Driver/Src/stm32l1xx_hal.d \
./ST_Code/Drivers/STM32L1xx_HAL_Driver/Src/stm32l1xx_hal_cortex.d \
./ST_Code/Drivers/STM32L1xx_HAL_Driver/Src/stm32l1xx_hal_dma.d \
./ST_Code/Drivers/STM32L1xx_HAL_Driver/Src/stm32l1xx_hal_flash.d \
./ST_Code/Drivers/STM32L1xx_HAL_Driver/Src/stm32l1xx_hal_flash_ex.d \
./ST_Code/Drivers/STM32L1xx_HAL_Driver/Src/stm32l1xx_hal_flash_ramfunc.d \
./ST_Code/Drivers/STM32L1xx_HAL_Driver/Src/stm32l1xx_hal_gpio.d \
./ST_Code/Drivers/STM32L1xx_HAL_Driver/Src/stm32l1xx_hal_pwr.d \
./ST_Code/Drivers/STM32L1xx_HAL_Driver/Src/stm32l1xx_hal_pwr_ex.d \
./ST_Code/Drivers/STM32L1xx_HAL_Driver/Src/stm32l1xx_hal_rcc.d \
./ST_Code/Drivers/STM32L1xx_HAL_Driver/Src/stm32l1xx_hal_rcc_ex.d \
./ST_Code/Drivers/STM32L1xx_HAL_Driver/Src/stm32l1xx_hal_tim.d \
./ST_Code/Drivers/STM32L1xx_HAL_Driver/Src/stm32l1xx_hal_tim_ex.d \
./ST_Code/Drivers/STM32L1xx_HAL_Driver/Src/stm32l1xx_hal_uart.d \
./ST_Code/Drivers/STM32L1xx_HAL_Driver/Src/stm32l1xx_ll_dma.d \
./ST_Code/Drivers/STM32L1xx_HAL_Driver/Src/stm32l1xx_ll_exti.d \
./ST_Code/Drivers/STM32L1xx_HAL_Driver/Src/stm32l1xx_ll_gpio.d \
./ST_Code/Drivers/STM32L1xx_HAL_Driver/Src/stm32l1xx_ll_pwr.d \
./ST_Code/Drivers/STM32L1xx_HAL_Driver/Src/stm32l1xx_ll_rcc.d \
./ST_Code/Drivers/STM32L1xx_HAL_Driver/Src/stm32l1xx_ll_usart.d \
./ST_Code/Drivers/STM32L1xx_HAL_Driver/Src/stm32l1xx_ll_utils.d 


# Each subdirectory must supply rules for building sources it contributes
ST_Code/Drivers/STM32L1xx_HAL_Driver/Src/stm32l1xx_hal.o: C:/Users/alejo/Documents/containers-project/D-Box/FreeRTOS/Demo/FreeRTOS-BOX-MODBUS_PID/ST_Code/Drivers/STM32L1xx_HAL_Driver/Src/stm32l1xx_hal.c ST_Code/Drivers/STM32L1xx_HAL_Driver/Src/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m3 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32L152xE -DDEBUG -DUSE_FULL_LL_DRIVER -c -I"C:/Users/alejo/Documents/containers-project/D-Box/FreeRTOS/Demo/FreeRTOS-BOX-MODBUS_PID/ST_Code/Drivers/CMSIS/Include" -I"C:/Users/alejo/Documents/containers-project/D-Box/FreeRTOS/Demo/FreeRTOS-BOX-MODBUS_PID/ST_Code/Drivers/STM32L1xx_HAL_Driver/Inc" -I"C:/Users/alejo/Documents/containers-project/D-Box/FreeRTOS/Demo/FreeRTOS-BOX-MODBUS_PID/ST_Code/Drivers/STM32L1xx_HAL_Driver/Inc/Legacy" -I"C:/Users/alejo/Documents/containers-project/D-Box/FreeRTOS/Demo/FreeRTOS-BOX-MODBUS_PID/ST_Code/Drivers/CMSIS/Device/ST/STM32L1xx/Include" -I"C:/Users/alejo/Documents/containers-project/D-Box/FreeRTOS/Demo/FreeRTOS-BOX-MODBUS_PID/Config" -I"C:/Users/alejo/Documents/containers-project/D-Box/FreeRTOS/Source/include" -I"C:/Users/alejo/Documents/containers-project/D-Box/FreeRTOS/Source/portable/GCC/ARM_CM3_MPU" -I"C:/Users/alejo/Documents/containers-project/D-Box/FreeRTOS/Demo/FreeRTOS-BOX-MODBUS_PID/ST_Code/Core/Inc" -I"C:/Users/alejo/Documents/containers-project/D-Box/MODBUS-LIB/Inc" -I"C:/Users/alejo/Documents/containers-project/D-Box/TRACE-LIB/config" -I"C:/Users/alejo/Documents/containers-project/D-Box/TRACE-LIB/include" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
ST_Code/Drivers/STM32L1xx_HAL_Driver/Src/stm32l1xx_hal_cortex.o: C:/Users/alejo/Documents/containers-project/D-Box/FreeRTOS/Demo/FreeRTOS-BOX-MODBUS_PID/ST_Code/Drivers/STM32L1xx_HAL_Driver/Src/stm32l1xx_hal_cortex.c ST_Code/Drivers/STM32L1xx_HAL_Driver/Src/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m3 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32L152xE -DDEBUG -DUSE_FULL_LL_DRIVER -c -I"C:/Users/alejo/Documents/containers-project/D-Box/FreeRTOS/Demo/FreeRTOS-BOX-MODBUS_PID/ST_Code/Drivers/CMSIS/Include" -I"C:/Users/alejo/Documents/containers-project/D-Box/FreeRTOS/Demo/FreeRTOS-BOX-MODBUS_PID/ST_Code/Drivers/STM32L1xx_HAL_Driver/Inc" -I"C:/Users/alejo/Documents/containers-project/D-Box/FreeRTOS/Demo/FreeRTOS-BOX-MODBUS_PID/ST_Code/Drivers/STM32L1xx_HAL_Driver/Inc/Legacy" -I"C:/Users/alejo/Documents/containers-project/D-Box/FreeRTOS/Demo/FreeRTOS-BOX-MODBUS_PID/ST_Code/Drivers/CMSIS/Device/ST/STM32L1xx/Include" -I"C:/Users/alejo/Documents/containers-project/D-Box/FreeRTOS/Demo/FreeRTOS-BOX-MODBUS_PID/Config" -I"C:/Users/alejo/Documents/containers-project/D-Box/FreeRTOS/Source/include" -I"C:/Users/alejo/Documents/containers-project/D-Box/FreeRTOS/Source/portable/GCC/ARM_CM3_MPU" -I"C:/Users/alejo/Documents/containers-project/D-Box/FreeRTOS/Demo/FreeRTOS-BOX-MODBUS_PID/ST_Code/Core/Inc" -I"C:/Users/alejo/Documents/containers-project/D-Box/MODBUS-LIB/Inc" -I"C:/Users/alejo/Documents/containers-project/D-Box/TRACE-LIB/config" -I"C:/Users/alejo/Documents/containers-project/D-Box/TRACE-LIB/include" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
ST_Code/Drivers/STM32L1xx_HAL_Driver/Src/stm32l1xx_hal_dma.o: C:/Users/alejo/Documents/containers-project/D-Box/FreeRTOS/Demo/FreeRTOS-BOX-MODBUS_PID/ST_Code/Drivers/STM32L1xx_HAL_Driver/Src/stm32l1xx_hal_dma.c ST_Code/Drivers/STM32L1xx_HAL_Driver/Src/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m3 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32L152xE -DDEBUG -DUSE_FULL_LL_DRIVER -c -I"C:/Users/alejo/Documents/containers-project/D-Box/FreeRTOS/Demo/FreeRTOS-BOX-MODBUS_PID/ST_Code/Drivers/CMSIS/Include" -I"C:/Users/alejo/Documents/containers-project/D-Box/FreeRTOS/Demo/FreeRTOS-BOX-MODBUS_PID/ST_Code/Drivers/STM32L1xx_HAL_Driver/Inc" -I"C:/Users/alejo/Documents/containers-project/D-Box/FreeRTOS/Demo/FreeRTOS-BOX-MODBUS_PID/ST_Code/Drivers/STM32L1xx_HAL_Driver/Inc/Legacy" -I"C:/Users/alejo/Documents/containers-project/D-Box/FreeRTOS/Demo/FreeRTOS-BOX-MODBUS_PID/ST_Code/Drivers/CMSIS/Device/ST/STM32L1xx/Include" -I"C:/Users/alejo/Documents/containers-project/D-Box/FreeRTOS/Demo/FreeRTOS-BOX-MODBUS_PID/Config" -I"C:/Users/alejo/Documents/containers-project/D-Box/FreeRTOS/Source/include" -I"C:/Users/alejo/Documents/containers-project/D-Box/FreeRTOS/Source/portable/GCC/ARM_CM3_MPU" -I"C:/Users/alejo/Documents/containers-project/D-Box/FreeRTOS/Demo/FreeRTOS-BOX-MODBUS_PID/ST_Code/Core/Inc" -I"C:/Users/alejo/Documents/containers-project/D-Box/MODBUS-LIB/Inc" -I"C:/Users/alejo/Documents/containers-project/D-Box/TRACE-LIB/config" -I"C:/Users/alejo/Documents/containers-project/D-Box/TRACE-LIB/include" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
ST_Code/Drivers/STM32L1xx_HAL_Driver/Src/stm32l1xx_hal_flash.o: C:/Users/alejo/Documents/containers-project/D-Box/FreeRTOS/Demo/FreeRTOS-BOX-MODBUS_PID/ST_Code/Drivers/STM32L1xx_HAL_Driver/Src/stm32l1xx_hal_flash.c ST_Code/Drivers/STM32L1xx_HAL_Driver/Src/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m3 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32L152xE -DDEBUG -DUSE_FULL_LL_DRIVER -c -I"C:/Users/alejo/Documents/containers-project/D-Box/FreeRTOS/Demo/FreeRTOS-BOX-MODBUS_PID/ST_Code/Drivers/CMSIS/Include" -I"C:/Users/alejo/Documents/containers-project/D-Box/FreeRTOS/Demo/FreeRTOS-BOX-MODBUS_PID/ST_Code/Drivers/STM32L1xx_HAL_Driver/Inc" -I"C:/Users/alejo/Documents/containers-project/D-Box/FreeRTOS/Demo/FreeRTOS-BOX-MODBUS_PID/ST_Code/Drivers/STM32L1xx_HAL_Driver/Inc/Legacy" -I"C:/Users/alejo/Documents/containers-project/D-Box/FreeRTOS/Demo/FreeRTOS-BOX-MODBUS_PID/ST_Code/Drivers/CMSIS/Device/ST/STM32L1xx/Include" -I"C:/Users/alejo/Documents/containers-project/D-Box/FreeRTOS/Demo/FreeRTOS-BOX-MODBUS_PID/Config" -I"C:/Users/alejo/Documents/containers-project/D-Box/FreeRTOS/Source/include" -I"C:/Users/alejo/Documents/containers-project/D-Box/FreeRTOS/Source/portable/GCC/ARM_CM3_MPU" -I"C:/Users/alejo/Documents/containers-project/D-Box/FreeRTOS/Demo/FreeRTOS-BOX-MODBUS_PID/ST_Code/Core/Inc" -I"C:/Users/alejo/Documents/containers-project/D-Box/MODBUS-LIB/Inc" -I"C:/Users/alejo/Documents/containers-project/D-Box/TRACE-LIB/config" -I"C:/Users/alejo/Documents/containers-project/D-Box/TRACE-LIB/include" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
ST_Code/Drivers/STM32L1xx_HAL_Driver/Src/stm32l1xx_hal_flash_ex.o: C:/Users/alejo/Documents/containers-project/D-Box/FreeRTOS/Demo/FreeRTOS-BOX-MODBUS_PID/ST_Code/Drivers/STM32L1xx_HAL_Driver/Src/stm32l1xx_hal_flash_ex.c ST_Code/Drivers/STM32L1xx_HAL_Driver/Src/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m3 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32L152xE -DDEBUG -DUSE_FULL_LL_DRIVER -c -I"C:/Users/alejo/Documents/containers-project/D-Box/FreeRTOS/Demo/FreeRTOS-BOX-MODBUS_PID/ST_Code/Drivers/CMSIS/Include" -I"C:/Users/alejo/Documents/containers-project/D-Box/FreeRTOS/Demo/FreeRTOS-BOX-MODBUS_PID/ST_Code/Drivers/STM32L1xx_HAL_Driver/Inc" -I"C:/Users/alejo/Documents/containers-project/D-Box/FreeRTOS/Demo/FreeRTOS-BOX-MODBUS_PID/ST_Code/Drivers/STM32L1xx_HAL_Driver/Inc/Legacy" -I"C:/Users/alejo/Documents/containers-project/D-Box/FreeRTOS/Demo/FreeRTOS-BOX-MODBUS_PID/ST_Code/Drivers/CMSIS/Device/ST/STM32L1xx/Include" -I"C:/Users/alejo/Documents/containers-project/D-Box/FreeRTOS/Demo/FreeRTOS-BOX-MODBUS_PID/Config" -I"C:/Users/alejo/Documents/containers-project/D-Box/FreeRTOS/Source/include" -I"C:/Users/alejo/Documents/containers-project/D-Box/FreeRTOS/Source/portable/GCC/ARM_CM3_MPU" -I"C:/Users/alejo/Documents/containers-project/D-Box/FreeRTOS/Demo/FreeRTOS-BOX-MODBUS_PID/ST_Code/Core/Inc" -I"C:/Users/alejo/Documents/containers-project/D-Box/MODBUS-LIB/Inc" -I"C:/Users/alejo/Documents/containers-project/D-Box/TRACE-LIB/config" -I"C:/Users/alejo/Documents/containers-project/D-Box/TRACE-LIB/include" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
ST_Code/Drivers/STM32L1xx_HAL_Driver/Src/stm32l1xx_hal_flash_ramfunc.o: C:/Users/alejo/Documents/containers-project/D-Box/FreeRTOS/Demo/FreeRTOS-BOX-MODBUS_PID/ST_Code/Drivers/STM32L1xx_HAL_Driver/Src/stm32l1xx_hal_flash_ramfunc.c ST_Code/Drivers/STM32L1xx_HAL_Driver/Src/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m3 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32L152xE -DDEBUG -DUSE_FULL_LL_DRIVER -c -I"C:/Users/alejo/Documents/containers-project/D-Box/FreeRTOS/Demo/FreeRTOS-BOX-MODBUS_PID/ST_Code/Drivers/CMSIS/Include" -I"C:/Users/alejo/Documents/containers-project/D-Box/FreeRTOS/Demo/FreeRTOS-BOX-MODBUS_PID/ST_Code/Drivers/STM32L1xx_HAL_Driver/Inc" -I"C:/Users/alejo/Documents/containers-project/D-Box/FreeRTOS/Demo/FreeRTOS-BOX-MODBUS_PID/ST_Code/Drivers/STM32L1xx_HAL_Driver/Inc/Legacy" -I"C:/Users/alejo/Documents/containers-project/D-Box/FreeRTOS/Demo/FreeRTOS-BOX-MODBUS_PID/ST_Code/Drivers/CMSIS/Device/ST/STM32L1xx/Include" -I"C:/Users/alejo/Documents/containers-project/D-Box/FreeRTOS/Demo/FreeRTOS-BOX-MODBUS_PID/Config" -I"C:/Users/alejo/Documents/containers-project/D-Box/FreeRTOS/Source/include" -I"C:/Users/alejo/Documents/containers-project/D-Box/FreeRTOS/Source/portable/GCC/ARM_CM3_MPU" -I"C:/Users/alejo/Documents/containers-project/D-Box/FreeRTOS/Demo/FreeRTOS-BOX-MODBUS_PID/ST_Code/Core/Inc" -I"C:/Users/alejo/Documents/containers-project/D-Box/MODBUS-LIB/Inc" -I"C:/Users/alejo/Documents/containers-project/D-Box/TRACE-LIB/config" -I"C:/Users/alejo/Documents/containers-project/D-Box/TRACE-LIB/include" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
ST_Code/Drivers/STM32L1xx_HAL_Driver/Src/stm32l1xx_hal_gpio.o: C:/Users/alejo/Documents/containers-project/D-Box/FreeRTOS/Demo/FreeRTOS-BOX-MODBUS_PID/ST_Code/Drivers/STM32L1xx_HAL_Driver/Src/stm32l1xx_hal_gpio.c ST_Code/Drivers/STM32L1xx_HAL_Driver/Src/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m3 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32L152xE -DDEBUG -DUSE_FULL_LL_DRIVER -c -I"C:/Users/alejo/Documents/containers-project/D-Box/FreeRTOS/Demo/FreeRTOS-BOX-MODBUS_PID/ST_Code/Drivers/CMSIS/Include" -I"C:/Users/alejo/Documents/containers-project/D-Box/FreeRTOS/Demo/FreeRTOS-BOX-MODBUS_PID/ST_Code/Drivers/STM32L1xx_HAL_Driver/Inc" -I"C:/Users/alejo/Documents/containers-project/D-Box/FreeRTOS/Demo/FreeRTOS-BOX-MODBUS_PID/ST_Code/Drivers/STM32L1xx_HAL_Driver/Inc/Legacy" -I"C:/Users/alejo/Documents/containers-project/D-Box/FreeRTOS/Demo/FreeRTOS-BOX-MODBUS_PID/ST_Code/Drivers/CMSIS/Device/ST/STM32L1xx/Include" -I"C:/Users/alejo/Documents/containers-project/D-Box/FreeRTOS/Demo/FreeRTOS-BOX-MODBUS_PID/Config" -I"C:/Users/alejo/Documents/containers-project/D-Box/FreeRTOS/Source/include" -I"C:/Users/alejo/Documents/containers-project/D-Box/FreeRTOS/Source/portable/GCC/ARM_CM3_MPU" -I"C:/Users/alejo/Documents/containers-project/D-Box/FreeRTOS/Demo/FreeRTOS-BOX-MODBUS_PID/ST_Code/Core/Inc" -I"C:/Users/alejo/Documents/containers-project/D-Box/MODBUS-LIB/Inc" -I"C:/Users/alejo/Documents/containers-project/D-Box/TRACE-LIB/config" -I"C:/Users/alejo/Documents/containers-project/D-Box/TRACE-LIB/include" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
ST_Code/Drivers/STM32L1xx_HAL_Driver/Src/stm32l1xx_hal_pwr.o: C:/Users/alejo/Documents/containers-project/D-Box/FreeRTOS/Demo/FreeRTOS-BOX-MODBUS_PID/ST_Code/Drivers/STM32L1xx_HAL_Driver/Src/stm32l1xx_hal_pwr.c ST_Code/Drivers/STM32L1xx_HAL_Driver/Src/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m3 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32L152xE -DDEBUG -DUSE_FULL_LL_DRIVER -c -I"C:/Users/alejo/Documents/containers-project/D-Box/FreeRTOS/Demo/FreeRTOS-BOX-MODBUS_PID/ST_Code/Drivers/CMSIS/Include" -I"C:/Users/alejo/Documents/containers-project/D-Box/FreeRTOS/Demo/FreeRTOS-BOX-MODBUS_PID/ST_Code/Drivers/STM32L1xx_HAL_Driver/Inc" -I"C:/Users/alejo/Documents/containers-project/D-Box/FreeRTOS/Demo/FreeRTOS-BOX-MODBUS_PID/ST_Code/Drivers/STM32L1xx_HAL_Driver/Inc/Legacy" -I"C:/Users/alejo/Documents/containers-project/D-Box/FreeRTOS/Demo/FreeRTOS-BOX-MODBUS_PID/ST_Code/Drivers/CMSIS/Device/ST/STM32L1xx/Include" -I"C:/Users/alejo/Documents/containers-project/D-Box/FreeRTOS/Demo/FreeRTOS-BOX-MODBUS_PID/Config" -I"C:/Users/alejo/Documents/containers-project/D-Box/FreeRTOS/Source/include" -I"C:/Users/alejo/Documents/containers-project/D-Box/FreeRTOS/Source/portable/GCC/ARM_CM3_MPU" -I"C:/Users/alejo/Documents/containers-project/D-Box/FreeRTOS/Demo/FreeRTOS-BOX-MODBUS_PID/ST_Code/Core/Inc" -I"C:/Users/alejo/Documents/containers-project/D-Box/MODBUS-LIB/Inc" -I"C:/Users/alejo/Documents/containers-project/D-Box/TRACE-LIB/config" -I"C:/Users/alejo/Documents/containers-project/D-Box/TRACE-LIB/include" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
ST_Code/Drivers/STM32L1xx_HAL_Driver/Src/stm32l1xx_hal_pwr_ex.o: C:/Users/alejo/Documents/containers-project/D-Box/FreeRTOS/Demo/FreeRTOS-BOX-MODBUS_PID/ST_Code/Drivers/STM32L1xx_HAL_Driver/Src/stm32l1xx_hal_pwr_ex.c ST_Code/Drivers/STM32L1xx_HAL_Driver/Src/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m3 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32L152xE -DDEBUG -DUSE_FULL_LL_DRIVER -c -I"C:/Users/alejo/Documents/containers-project/D-Box/FreeRTOS/Demo/FreeRTOS-BOX-MODBUS_PID/ST_Code/Drivers/CMSIS/Include" -I"C:/Users/alejo/Documents/containers-project/D-Box/FreeRTOS/Demo/FreeRTOS-BOX-MODBUS_PID/ST_Code/Drivers/STM32L1xx_HAL_Driver/Inc" -I"C:/Users/alejo/Documents/containers-project/D-Box/FreeRTOS/Demo/FreeRTOS-BOX-MODBUS_PID/ST_Code/Drivers/STM32L1xx_HAL_Driver/Inc/Legacy" -I"C:/Users/alejo/Documents/containers-project/D-Box/FreeRTOS/Demo/FreeRTOS-BOX-MODBUS_PID/ST_Code/Drivers/CMSIS/Device/ST/STM32L1xx/Include" -I"C:/Users/alejo/Documents/containers-project/D-Box/FreeRTOS/Demo/FreeRTOS-BOX-MODBUS_PID/Config" -I"C:/Users/alejo/Documents/containers-project/D-Box/FreeRTOS/Source/include" -I"C:/Users/alejo/Documents/containers-project/D-Box/FreeRTOS/Source/portable/GCC/ARM_CM3_MPU" -I"C:/Users/alejo/Documents/containers-project/D-Box/FreeRTOS/Demo/FreeRTOS-BOX-MODBUS_PID/ST_Code/Core/Inc" -I"C:/Users/alejo/Documents/containers-project/D-Box/MODBUS-LIB/Inc" -I"C:/Users/alejo/Documents/containers-project/D-Box/TRACE-LIB/config" -I"C:/Users/alejo/Documents/containers-project/D-Box/TRACE-LIB/include" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
ST_Code/Drivers/STM32L1xx_HAL_Driver/Src/stm32l1xx_hal_rcc.o: C:/Users/alejo/Documents/containers-project/D-Box/FreeRTOS/Demo/FreeRTOS-BOX-MODBUS_PID/ST_Code/Drivers/STM32L1xx_HAL_Driver/Src/stm32l1xx_hal_rcc.c ST_Code/Drivers/STM32L1xx_HAL_Driver/Src/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m3 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32L152xE -DDEBUG -DUSE_FULL_LL_DRIVER -c -I"C:/Users/alejo/Documents/containers-project/D-Box/FreeRTOS/Demo/FreeRTOS-BOX-MODBUS_PID/ST_Code/Drivers/CMSIS/Include" -I"C:/Users/alejo/Documents/containers-project/D-Box/FreeRTOS/Demo/FreeRTOS-BOX-MODBUS_PID/ST_Code/Drivers/STM32L1xx_HAL_Driver/Inc" -I"C:/Users/alejo/Documents/containers-project/D-Box/FreeRTOS/Demo/FreeRTOS-BOX-MODBUS_PID/ST_Code/Drivers/STM32L1xx_HAL_Driver/Inc/Legacy" -I"C:/Users/alejo/Documents/containers-project/D-Box/FreeRTOS/Demo/FreeRTOS-BOX-MODBUS_PID/ST_Code/Drivers/CMSIS/Device/ST/STM32L1xx/Include" -I"C:/Users/alejo/Documents/containers-project/D-Box/FreeRTOS/Demo/FreeRTOS-BOX-MODBUS_PID/Config" -I"C:/Users/alejo/Documents/containers-project/D-Box/FreeRTOS/Source/include" -I"C:/Users/alejo/Documents/containers-project/D-Box/FreeRTOS/Source/portable/GCC/ARM_CM3_MPU" -I"C:/Users/alejo/Documents/containers-project/D-Box/FreeRTOS/Demo/FreeRTOS-BOX-MODBUS_PID/ST_Code/Core/Inc" -I"C:/Users/alejo/Documents/containers-project/D-Box/MODBUS-LIB/Inc" -I"C:/Users/alejo/Documents/containers-project/D-Box/TRACE-LIB/config" -I"C:/Users/alejo/Documents/containers-project/D-Box/TRACE-LIB/include" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
ST_Code/Drivers/STM32L1xx_HAL_Driver/Src/stm32l1xx_hal_rcc_ex.o: C:/Users/alejo/Documents/containers-project/D-Box/FreeRTOS/Demo/FreeRTOS-BOX-MODBUS_PID/ST_Code/Drivers/STM32L1xx_HAL_Driver/Src/stm32l1xx_hal_rcc_ex.c ST_Code/Drivers/STM32L1xx_HAL_Driver/Src/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m3 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32L152xE -DDEBUG -DUSE_FULL_LL_DRIVER -c -I"C:/Users/alejo/Documents/containers-project/D-Box/FreeRTOS/Demo/FreeRTOS-BOX-MODBUS_PID/ST_Code/Drivers/CMSIS/Include" -I"C:/Users/alejo/Documents/containers-project/D-Box/FreeRTOS/Demo/FreeRTOS-BOX-MODBUS_PID/ST_Code/Drivers/STM32L1xx_HAL_Driver/Inc" -I"C:/Users/alejo/Documents/containers-project/D-Box/FreeRTOS/Demo/FreeRTOS-BOX-MODBUS_PID/ST_Code/Drivers/STM32L1xx_HAL_Driver/Inc/Legacy" -I"C:/Users/alejo/Documents/containers-project/D-Box/FreeRTOS/Demo/FreeRTOS-BOX-MODBUS_PID/ST_Code/Drivers/CMSIS/Device/ST/STM32L1xx/Include" -I"C:/Users/alejo/Documents/containers-project/D-Box/FreeRTOS/Demo/FreeRTOS-BOX-MODBUS_PID/Config" -I"C:/Users/alejo/Documents/containers-project/D-Box/FreeRTOS/Source/include" -I"C:/Users/alejo/Documents/containers-project/D-Box/FreeRTOS/Source/portable/GCC/ARM_CM3_MPU" -I"C:/Users/alejo/Documents/containers-project/D-Box/FreeRTOS/Demo/FreeRTOS-BOX-MODBUS_PID/ST_Code/Core/Inc" -I"C:/Users/alejo/Documents/containers-project/D-Box/MODBUS-LIB/Inc" -I"C:/Users/alejo/Documents/containers-project/D-Box/TRACE-LIB/config" -I"C:/Users/alejo/Documents/containers-project/D-Box/TRACE-LIB/include" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
ST_Code/Drivers/STM32L1xx_HAL_Driver/Src/stm32l1xx_hal_tim.o: C:/Users/alejo/Documents/containers-project/D-Box/FreeRTOS/Demo/FreeRTOS-BOX-MODBUS_PID/ST_Code/Drivers/STM32L1xx_HAL_Driver/Src/stm32l1xx_hal_tim.c ST_Code/Drivers/STM32L1xx_HAL_Driver/Src/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m3 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32L152xE -DDEBUG -DUSE_FULL_LL_DRIVER -c -I"C:/Users/alejo/Documents/containers-project/D-Box/FreeRTOS/Demo/FreeRTOS-BOX-MODBUS_PID/ST_Code/Drivers/CMSIS/Include" -I"C:/Users/alejo/Documents/containers-project/D-Box/FreeRTOS/Demo/FreeRTOS-BOX-MODBUS_PID/ST_Code/Drivers/STM32L1xx_HAL_Driver/Inc" -I"C:/Users/alejo/Documents/containers-project/D-Box/FreeRTOS/Demo/FreeRTOS-BOX-MODBUS_PID/ST_Code/Drivers/STM32L1xx_HAL_Driver/Inc/Legacy" -I"C:/Users/alejo/Documents/containers-project/D-Box/FreeRTOS/Demo/FreeRTOS-BOX-MODBUS_PID/ST_Code/Drivers/CMSIS/Device/ST/STM32L1xx/Include" -I"C:/Users/alejo/Documents/containers-project/D-Box/FreeRTOS/Demo/FreeRTOS-BOX-MODBUS_PID/Config" -I"C:/Users/alejo/Documents/containers-project/D-Box/FreeRTOS/Source/include" -I"C:/Users/alejo/Documents/containers-project/D-Box/FreeRTOS/Source/portable/GCC/ARM_CM3_MPU" -I"C:/Users/alejo/Documents/containers-project/D-Box/FreeRTOS/Demo/FreeRTOS-BOX-MODBUS_PID/ST_Code/Core/Inc" -I"C:/Users/alejo/Documents/containers-project/D-Box/MODBUS-LIB/Inc" -I"C:/Users/alejo/Documents/containers-project/D-Box/TRACE-LIB/config" -I"C:/Users/alejo/Documents/containers-project/D-Box/TRACE-LIB/include" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
ST_Code/Drivers/STM32L1xx_HAL_Driver/Src/stm32l1xx_hal_tim_ex.o: C:/Users/alejo/Documents/containers-project/D-Box/FreeRTOS/Demo/FreeRTOS-BOX-MODBUS_PID/ST_Code/Drivers/STM32L1xx_HAL_Driver/Src/stm32l1xx_hal_tim_ex.c ST_Code/Drivers/STM32L1xx_HAL_Driver/Src/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m3 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32L152xE -DDEBUG -DUSE_FULL_LL_DRIVER -c -I"C:/Users/alejo/Documents/containers-project/D-Box/FreeRTOS/Demo/FreeRTOS-BOX-MODBUS_PID/ST_Code/Drivers/CMSIS/Include" -I"C:/Users/alejo/Documents/containers-project/D-Box/FreeRTOS/Demo/FreeRTOS-BOX-MODBUS_PID/ST_Code/Drivers/STM32L1xx_HAL_Driver/Inc" -I"C:/Users/alejo/Documents/containers-project/D-Box/FreeRTOS/Demo/FreeRTOS-BOX-MODBUS_PID/ST_Code/Drivers/STM32L1xx_HAL_Driver/Inc/Legacy" -I"C:/Users/alejo/Documents/containers-project/D-Box/FreeRTOS/Demo/FreeRTOS-BOX-MODBUS_PID/ST_Code/Drivers/CMSIS/Device/ST/STM32L1xx/Include" -I"C:/Users/alejo/Documents/containers-project/D-Box/FreeRTOS/Demo/FreeRTOS-BOX-MODBUS_PID/Config" -I"C:/Users/alejo/Documents/containers-project/D-Box/FreeRTOS/Source/include" -I"C:/Users/alejo/Documents/containers-project/D-Box/FreeRTOS/Source/portable/GCC/ARM_CM3_MPU" -I"C:/Users/alejo/Documents/containers-project/D-Box/FreeRTOS/Demo/FreeRTOS-BOX-MODBUS_PID/ST_Code/Core/Inc" -I"C:/Users/alejo/Documents/containers-project/D-Box/MODBUS-LIB/Inc" -I"C:/Users/alejo/Documents/containers-project/D-Box/TRACE-LIB/config" -I"C:/Users/alejo/Documents/containers-project/D-Box/TRACE-LIB/include" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
ST_Code/Drivers/STM32L1xx_HAL_Driver/Src/stm32l1xx_hal_uart.o: C:/Users/alejo/Documents/containers-project/D-Box/FreeRTOS/Demo/FreeRTOS-BOX-MODBUS_PID/ST_Code/Drivers/STM32L1xx_HAL_Driver/Src/stm32l1xx_hal_uart.c ST_Code/Drivers/STM32L1xx_HAL_Driver/Src/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m3 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32L152xE -DDEBUG -DUSE_FULL_LL_DRIVER -c -I"C:/Users/alejo/Documents/containers-project/D-Box/FreeRTOS/Demo/FreeRTOS-BOX-MODBUS_PID/ST_Code/Drivers/CMSIS/Include" -I"C:/Users/alejo/Documents/containers-project/D-Box/FreeRTOS/Demo/FreeRTOS-BOX-MODBUS_PID/ST_Code/Drivers/STM32L1xx_HAL_Driver/Inc" -I"C:/Users/alejo/Documents/containers-project/D-Box/FreeRTOS/Demo/FreeRTOS-BOX-MODBUS_PID/ST_Code/Drivers/STM32L1xx_HAL_Driver/Inc/Legacy" -I"C:/Users/alejo/Documents/containers-project/D-Box/FreeRTOS/Demo/FreeRTOS-BOX-MODBUS_PID/ST_Code/Drivers/CMSIS/Device/ST/STM32L1xx/Include" -I"C:/Users/alejo/Documents/containers-project/D-Box/FreeRTOS/Demo/FreeRTOS-BOX-MODBUS_PID/Config" -I"C:/Users/alejo/Documents/containers-project/D-Box/FreeRTOS/Source/include" -I"C:/Users/alejo/Documents/containers-project/D-Box/FreeRTOS/Source/portable/GCC/ARM_CM3_MPU" -I"C:/Users/alejo/Documents/containers-project/D-Box/FreeRTOS/Demo/FreeRTOS-BOX-MODBUS_PID/ST_Code/Core/Inc" -I"C:/Users/alejo/Documents/containers-project/D-Box/MODBUS-LIB/Inc" -I"C:/Users/alejo/Documents/containers-project/D-Box/TRACE-LIB/config" -I"C:/Users/alejo/Documents/containers-project/D-Box/TRACE-LIB/include" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
ST_Code/Drivers/STM32L1xx_HAL_Driver/Src/stm32l1xx_ll_dma.o: C:/Users/alejo/Documents/containers-project/D-Box/FreeRTOS/Demo/FreeRTOS-BOX-MODBUS_PID/ST_Code/Drivers/STM32L1xx_HAL_Driver/Src/stm32l1xx_ll_dma.c ST_Code/Drivers/STM32L1xx_HAL_Driver/Src/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m3 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32L152xE -DDEBUG -DUSE_FULL_LL_DRIVER -c -I"C:/Users/alejo/Documents/containers-project/D-Box/FreeRTOS/Demo/FreeRTOS-BOX-MODBUS_PID/ST_Code/Drivers/CMSIS/Include" -I"C:/Users/alejo/Documents/containers-project/D-Box/FreeRTOS/Demo/FreeRTOS-BOX-MODBUS_PID/ST_Code/Drivers/STM32L1xx_HAL_Driver/Inc" -I"C:/Users/alejo/Documents/containers-project/D-Box/FreeRTOS/Demo/FreeRTOS-BOX-MODBUS_PID/ST_Code/Drivers/STM32L1xx_HAL_Driver/Inc/Legacy" -I"C:/Users/alejo/Documents/containers-project/D-Box/FreeRTOS/Demo/FreeRTOS-BOX-MODBUS_PID/ST_Code/Drivers/CMSIS/Device/ST/STM32L1xx/Include" -I"C:/Users/alejo/Documents/containers-project/D-Box/FreeRTOS/Demo/FreeRTOS-BOX-MODBUS_PID/Config" -I"C:/Users/alejo/Documents/containers-project/D-Box/FreeRTOS/Source/include" -I"C:/Users/alejo/Documents/containers-project/D-Box/FreeRTOS/Source/portable/GCC/ARM_CM3_MPU" -I"C:/Users/alejo/Documents/containers-project/D-Box/FreeRTOS/Demo/FreeRTOS-BOX-MODBUS_PID/ST_Code/Core/Inc" -I"C:/Users/alejo/Documents/containers-project/D-Box/MODBUS-LIB/Inc" -I"C:/Users/alejo/Documents/containers-project/D-Box/TRACE-LIB/config" -I"C:/Users/alejo/Documents/containers-project/D-Box/TRACE-LIB/include" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
ST_Code/Drivers/STM32L1xx_HAL_Driver/Src/stm32l1xx_ll_exti.o: C:/Users/alejo/Documents/containers-project/D-Box/FreeRTOS/Demo/FreeRTOS-BOX-MODBUS_PID/ST_Code/Drivers/STM32L1xx_HAL_Driver/Src/stm32l1xx_ll_exti.c ST_Code/Drivers/STM32L1xx_HAL_Driver/Src/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m3 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32L152xE -DDEBUG -DUSE_FULL_LL_DRIVER -c -I"C:/Users/alejo/Documents/containers-project/D-Box/FreeRTOS/Demo/FreeRTOS-BOX-MODBUS_PID/ST_Code/Drivers/CMSIS/Include" -I"C:/Users/alejo/Documents/containers-project/D-Box/FreeRTOS/Demo/FreeRTOS-BOX-MODBUS_PID/ST_Code/Drivers/STM32L1xx_HAL_Driver/Inc" -I"C:/Users/alejo/Documents/containers-project/D-Box/FreeRTOS/Demo/FreeRTOS-BOX-MODBUS_PID/ST_Code/Drivers/STM32L1xx_HAL_Driver/Inc/Legacy" -I"C:/Users/alejo/Documents/containers-project/D-Box/FreeRTOS/Demo/FreeRTOS-BOX-MODBUS_PID/ST_Code/Drivers/CMSIS/Device/ST/STM32L1xx/Include" -I"C:/Users/alejo/Documents/containers-project/D-Box/FreeRTOS/Demo/FreeRTOS-BOX-MODBUS_PID/Config" -I"C:/Users/alejo/Documents/containers-project/D-Box/FreeRTOS/Source/include" -I"C:/Users/alejo/Documents/containers-project/D-Box/FreeRTOS/Source/portable/GCC/ARM_CM3_MPU" -I"C:/Users/alejo/Documents/containers-project/D-Box/FreeRTOS/Demo/FreeRTOS-BOX-MODBUS_PID/ST_Code/Core/Inc" -I"C:/Users/alejo/Documents/containers-project/D-Box/MODBUS-LIB/Inc" -I"C:/Users/alejo/Documents/containers-project/D-Box/TRACE-LIB/config" -I"C:/Users/alejo/Documents/containers-project/D-Box/TRACE-LIB/include" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
ST_Code/Drivers/STM32L1xx_HAL_Driver/Src/stm32l1xx_ll_gpio.o: C:/Users/alejo/Documents/containers-project/D-Box/FreeRTOS/Demo/FreeRTOS-BOX-MODBUS_PID/ST_Code/Drivers/STM32L1xx_HAL_Driver/Src/stm32l1xx_ll_gpio.c ST_Code/Drivers/STM32L1xx_HAL_Driver/Src/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m3 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32L152xE -DDEBUG -DUSE_FULL_LL_DRIVER -c -I"C:/Users/alejo/Documents/containers-project/D-Box/FreeRTOS/Demo/FreeRTOS-BOX-MODBUS_PID/ST_Code/Drivers/CMSIS/Include" -I"C:/Users/alejo/Documents/containers-project/D-Box/FreeRTOS/Demo/FreeRTOS-BOX-MODBUS_PID/ST_Code/Drivers/STM32L1xx_HAL_Driver/Inc" -I"C:/Users/alejo/Documents/containers-project/D-Box/FreeRTOS/Demo/FreeRTOS-BOX-MODBUS_PID/ST_Code/Drivers/STM32L1xx_HAL_Driver/Inc/Legacy" -I"C:/Users/alejo/Documents/containers-project/D-Box/FreeRTOS/Demo/FreeRTOS-BOX-MODBUS_PID/ST_Code/Drivers/CMSIS/Device/ST/STM32L1xx/Include" -I"C:/Users/alejo/Documents/containers-project/D-Box/FreeRTOS/Demo/FreeRTOS-BOX-MODBUS_PID/Config" -I"C:/Users/alejo/Documents/containers-project/D-Box/FreeRTOS/Source/include" -I"C:/Users/alejo/Documents/containers-project/D-Box/FreeRTOS/Source/portable/GCC/ARM_CM3_MPU" -I"C:/Users/alejo/Documents/containers-project/D-Box/FreeRTOS/Demo/FreeRTOS-BOX-MODBUS_PID/ST_Code/Core/Inc" -I"C:/Users/alejo/Documents/containers-project/D-Box/MODBUS-LIB/Inc" -I"C:/Users/alejo/Documents/containers-project/D-Box/TRACE-LIB/config" -I"C:/Users/alejo/Documents/containers-project/D-Box/TRACE-LIB/include" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
ST_Code/Drivers/STM32L1xx_HAL_Driver/Src/stm32l1xx_ll_pwr.o: C:/Users/alejo/Documents/containers-project/D-Box/FreeRTOS/Demo/FreeRTOS-BOX-MODBUS_PID/ST_Code/Drivers/STM32L1xx_HAL_Driver/Src/stm32l1xx_ll_pwr.c ST_Code/Drivers/STM32L1xx_HAL_Driver/Src/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m3 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32L152xE -DDEBUG -DUSE_FULL_LL_DRIVER -c -I"C:/Users/alejo/Documents/containers-project/D-Box/FreeRTOS/Demo/FreeRTOS-BOX-MODBUS_PID/ST_Code/Drivers/CMSIS/Include" -I"C:/Users/alejo/Documents/containers-project/D-Box/FreeRTOS/Demo/FreeRTOS-BOX-MODBUS_PID/ST_Code/Drivers/STM32L1xx_HAL_Driver/Inc" -I"C:/Users/alejo/Documents/containers-project/D-Box/FreeRTOS/Demo/FreeRTOS-BOX-MODBUS_PID/ST_Code/Drivers/STM32L1xx_HAL_Driver/Inc/Legacy" -I"C:/Users/alejo/Documents/containers-project/D-Box/FreeRTOS/Demo/FreeRTOS-BOX-MODBUS_PID/ST_Code/Drivers/CMSIS/Device/ST/STM32L1xx/Include" -I"C:/Users/alejo/Documents/containers-project/D-Box/FreeRTOS/Demo/FreeRTOS-BOX-MODBUS_PID/Config" -I"C:/Users/alejo/Documents/containers-project/D-Box/FreeRTOS/Source/include" -I"C:/Users/alejo/Documents/containers-project/D-Box/FreeRTOS/Source/portable/GCC/ARM_CM3_MPU" -I"C:/Users/alejo/Documents/containers-project/D-Box/FreeRTOS/Demo/FreeRTOS-BOX-MODBUS_PID/ST_Code/Core/Inc" -I"C:/Users/alejo/Documents/containers-project/D-Box/MODBUS-LIB/Inc" -I"C:/Users/alejo/Documents/containers-project/D-Box/TRACE-LIB/config" -I"C:/Users/alejo/Documents/containers-project/D-Box/TRACE-LIB/include" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
ST_Code/Drivers/STM32L1xx_HAL_Driver/Src/stm32l1xx_ll_rcc.o: C:/Users/alejo/Documents/containers-project/D-Box/FreeRTOS/Demo/FreeRTOS-BOX-MODBUS_PID/ST_Code/Drivers/STM32L1xx_HAL_Driver/Src/stm32l1xx_ll_rcc.c ST_Code/Drivers/STM32L1xx_HAL_Driver/Src/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m3 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32L152xE -DDEBUG -DUSE_FULL_LL_DRIVER -c -I"C:/Users/alejo/Documents/containers-project/D-Box/FreeRTOS/Demo/FreeRTOS-BOX-MODBUS_PID/ST_Code/Drivers/CMSIS/Include" -I"C:/Users/alejo/Documents/containers-project/D-Box/FreeRTOS/Demo/FreeRTOS-BOX-MODBUS_PID/ST_Code/Drivers/STM32L1xx_HAL_Driver/Inc" -I"C:/Users/alejo/Documents/containers-project/D-Box/FreeRTOS/Demo/FreeRTOS-BOX-MODBUS_PID/ST_Code/Drivers/STM32L1xx_HAL_Driver/Inc/Legacy" -I"C:/Users/alejo/Documents/containers-project/D-Box/FreeRTOS/Demo/FreeRTOS-BOX-MODBUS_PID/ST_Code/Drivers/CMSIS/Device/ST/STM32L1xx/Include" -I"C:/Users/alejo/Documents/containers-project/D-Box/FreeRTOS/Demo/FreeRTOS-BOX-MODBUS_PID/Config" -I"C:/Users/alejo/Documents/containers-project/D-Box/FreeRTOS/Source/include" -I"C:/Users/alejo/Documents/containers-project/D-Box/FreeRTOS/Source/portable/GCC/ARM_CM3_MPU" -I"C:/Users/alejo/Documents/containers-project/D-Box/FreeRTOS/Demo/FreeRTOS-BOX-MODBUS_PID/ST_Code/Core/Inc" -I"C:/Users/alejo/Documents/containers-project/D-Box/MODBUS-LIB/Inc" -I"C:/Users/alejo/Documents/containers-project/D-Box/TRACE-LIB/config" -I"C:/Users/alejo/Documents/containers-project/D-Box/TRACE-LIB/include" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
ST_Code/Drivers/STM32L1xx_HAL_Driver/Src/stm32l1xx_ll_usart.o: C:/Users/alejo/Documents/containers-project/D-Box/FreeRTOS/Demo/FreeRTOS-BOX-MODBUS_PID/ST_Code/Drivers/STM32L1xx_HAL_Driver/Src/stm32l1xx_ll_usart.c ST_Code/Drivers/STM32L1xx_HAL_Driver/Src/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m3 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32L152xE -DDEBUG -DUSE_FULL_LL_DRIVER -c -I"C:/Users/alejo/Documents/containers-project/D-Box/FreeRTOS/Demo/FreeRTOS-BOX-MODBUS_PID/ST_Code/Drivers/CMSIS/Include" -I"C:/Users/alejo/Documents/containers-project/D-Box/FreeRTOS/Demo/FreeRTOS-BOX-MODBUS_PID/ST_Code/Drivers/STM32L1xx_HAL_Driver/Inc" -I"C:/Users/alejo/Documents/containers-project/D-Box/FreeRTOS/Demo/FreeRTOS-BOX-MODBUS_PID/ST_Code/Drivers/STM32L1xx_HAL_Driver/Inc/Legacy" -I"C:/Users/alejo/Documents/containers-project/D-Box/FreeRTOS/Demo/FreeRTOS-BOX-MODBUS_PID/ST_Code/Drivers/CMSIS/Device/ST/STM32L1xx/Include" -I"C:/Users/alejo/Documents/containers-project/D-Box/FreeRTOS/Demo/FreeRTOS-BOX-MODBUS_PID/Config" -I"C:/Users/alejo/Documents/containers-project/D-Box/FreeRTOS/Source/include" -I"C:/Users/alejo/Documents/containers-project/D-Box/FreeRTOS/Source/portable/GCC/ARM_CM3_MPU" -I"C:/Users/alejo/Documents/containers-project/D-Box/FreeRTOS/Demo/FreeRTOS-BOX-MODBUS_PID/ST_Code/Core/Inc" -I"C:/Users/alejo/Documents/containers-project/D-Box/MODBUS-LIB/Inc" -I"C:/Users/alejo/Documents/containers-project/D-Box/TRACE-LIB/config" -I"C:/Users/alejo/Documents/containers-project/D-Box/TRACE-LIB/include" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
ST_Code/Drivers/STM32L1xx_HAL_Driver/Src/stm32l1xx_ll_utils.o: C:/Users/alejo/Documents/containers-project/D-Box/FreeRTOS/Demo/FreeRTOS-BOX-MODBUS_PID/ST_Code/Drivers/STM32L1xx_HAL_Driver/Src/stm32l1xx_ll_utils.c ST_Code/Drivers/STM32L1xx_HAL_Driver/Src/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m3 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32L152xE -DDEBUG -DUSE_FULL_LL_DRIVER -c -I"C:/Users/alejo/Documents/containers-project/D-Box/FreeRTOS/Demo/FreeRTOS-BOX-MODBUS_PID/ST_Code/Drivers/CMSIS/Include" -I"C:/Users/alejo/Documents/containers-project/D-Box/FreeRTOS/Demo/FreeRTOS-BOX-MODBUS_PID/ST_Code/Drivers/STM32L1xx_HAL_Driver/Inc" -I"C:/Users/alejo/Documents/containers-project/D-Box/FreeRTOS/Demo/FreeRTOS-BOX-MODBUS_PID/ST_Code/Drivers/STM32L1xx_HAL_Driver/Inc/Legacy" -I"C:/Users/alejo/Documents/containers-project/D-Box/FreeRTOS/Demo/FreeRTOS-BOX-MODBUS_PID/ST_Code/Drivers/CMSIS/Device/ST/STM32L1xx/Include" -I"C:/Users/alejo/Documents/containers-project/D-Box/FreeRTOS/Demo/FreeRTOS-BOX-MODBUS_PID/Config" -I"C:/Users/alejo/Documents/containers-project/D-Box/FreeRTOS/Source/include" -I"C:/Users/alejo/Documents/containers-project/D-Box/FreeRTOS/Source/portable/GCC/ARM_CM3_MPU" -I"C:/Users/alejo/Documents/containers-project/D-Box/FreeRTOS/Demo/FreeRTOS-BOX-MODBUS_PID/ST_Code/Core/Inc" -I"C:/Users/alejo/Documents/containers-project/D-Box/MODBUS-LIB/Inc" -I"C:/Users/alejo/Documents/containers-project/D-Box/TRACE-LIB/config" -I"C:/Users/alejo/Documents/containers-project/D-Box/TRACE-LIB/include" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"

clean: clean-ST_Code-2f-Drivers-2f-STM32L1xx_HAL_Driver-2f-Src

clean-ST_Code-2f-Drivers-2f-STM32L1xx_HAL_Driver-2f-Src:
	-$(RM) ./ST_Code/Drivers/STM32L1xx_HAL_Driver/Src/stm32l1xx_hal.d ./ST_Code/Drivers/STM32L1xx_HAL_Driver/Src/stm32l1xx_hal.o ./ST_Code/Drivers/STM32L1xx_HAL_Driver/Src/stm32l1xx_hal_cortex.d ./ST_Code/Drivers/STM32L1xx_HAL_Driver/Src/stm32l1xx_hal_cortex.o ./ST_Code/Drivers/STM32L1xx_HAL_Driver/Src/stm32l1xx_hal_dma.d ./ST_Code/Drivers/STM32L1xx_HAL_Driver/Src/stm32l1xx_hal_dma.o ./ST_Code/Drivers/STM32L1xx_HAL_Driver/Src/stm32l1xx_hal_flash.d ./ST_Code/Drivers/STM32L1xx_HAL_Driver/Src/stm32l1xx_hal_flash.o ./ST_Code/Drivers/STM32L1xx_HAL_Driver/Src/stm32l1xx_hal_flash_ex.d ./ST_Code/Drivers/STM32L1xx_HAL_Driver/Src/stm32l1xx_hal_flash_ex.o ./ST_Code/Drivers/STM32L1xx_HAL_Driver/Src/stm32l1xx_hal_flash_ramfunc.d ./ST_Code/Drivers/STM32L1xx_HAL_Driver/Src/stm32l1xx_hal_flash_ramfunc.o ./ST_Code/Drivers/STM32L1xx_HAL_Driver/Src/stm32l1xx_hal_gpio.d ./ST_Code/Drivers/STM32L1xx_HAL_Driver/Src/stm32l1xx_hal_gpio.o ./ST_Code/Drivers/STM32L1xx_HAL_Driver/Src/stm32l1xx_hal_pwr.d ./ST_Code/Drivers/STM32L1xx_HAL_Driver/Src/stm32l1xx_hal_pwr.o ./ST_Code/Drivers/STM32L1xx_HAL_Driver/Src/stm32l1xx_hal_pwr_ex.d ./ST_Code/Drivers/STM32L1xx_HAL_Driver/Src/stm32l1xx_hal_pwr_ex.o ./ST_Code/Drivers/STM32L1xx_HAL_Driver/Src/stm32l1xx_hal_rcc.d ./ST_Code/Drivers/STM32L1xx_HAL_Driver/Src/stm32l1xx_hal_rcc.o ./ST_Code/Drivers/STM32L1xx_HAL_Driver/Src/stm32l1xx_hal_rcc_ex.d ./ST_Code/Drivers/STM32L1xx_HAL_Driver/Src/stm32l1xx_hal_rcc_ex.o ./ST_Code/Drivers/STM32L1xx_HAL_Driver/Src/stm32l1xx_hal_tim.d ./ST_Code/Drivers/STM32L1xx_HAL_Driver/Src/stm32l1xx_hal_tim.o ./ST_Code/Drivers/STM32L1xx_HAL_Driver/Src/stm32l1xx_hal_tim_ex.d ./ST_Code/Drivers/STM32L1xx_HAL_Driver/Src/stm32l1xx_hal_tim_ex.o ./ST_Code/Drivers/STM32L1xx_HAL_Driver/Src/stm32l1xx_hal_uart.d ./ST_Code/Drivers/STM32L1xx_HAL_Driver/Src/stm32l1xx_hal_uart.o ./ST_Code/Drivers/STM32L1xx_HAL_Driver/Src/stm32l1xx_ll_dma.d ./ST_Code/Drivers/STM32L1xx_HAL_Driver/Src/stm32l1xx_ll_dma.o ./ST_Code/Drivers/STM32L1xx_HAL_Driver/Src/stm32l1xx_ll_exti.d ./ST_Code/Drivers/STM32L1xx_HAL_Driver/Src/stm32l1xx_ll_exti.o ./ST_Code/Drivers/STM32L1xx_HAL_Driver/Src/stm32l1xx_ll_gpio.d ./ST_Code/Drivers/STM32L1xx_HAL_Driver/Src/stm32l1xx_ll_gpio.o ./ST_Code/Drivers/STM32L1xx_HAL_Driver/Src/stm32l1xx_ll_pwr.d ./ST_Code/Drivers/STM32L1xx_HAL_Driver/Src/stm32l1xx_ll_pwr.o ./ST_Code/Drivers/STM32L1xx_HAL_Driver/Src/stm32l1xx_ll_rcc.d ./ST_Code/Drivers/STM32L1xx_HAL_Driver/Src/stm32l1xx_ll_rcc.o ./ST_Code/Drivers/STM32L1xx_HAL_Driver/Src/stm32l1xx_ll_usart.d ./ST_Code/Drivers/STM32L1xx_HAL_Driver/Src/stm32l1xx_ll_usart.o ./ST_Code/Drivers/STM32L1xx_HAL_Driver/Src/stm32l1xx_ll_utils.d ./ST_Code/Drivers/STM32L1xx_HAL_Driver/Src/stm32l1xx_ll_utils.o

.PHONY: clean-ST_Code-2f-Drivers-2f-STM32L1xx_HAL_Driver-2f-Src

